version: '3.8'

services:
  server:
    build: ./
    container_name: DRAW
    stdin_open: true
    tty: true
    ports:
      - '8080:8080'
    volumes:
      - '.:/app'  
      - '/app/node_modules'    
    environment:
      - CHOKIDAR_USEPOLLING=true